version: '3.8'

services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
      - 9411:9411
    volumes:
      - ./tempo.yaml:/tempo.yaml  
    restart: always
    environment:
      - TZ=Asia/Taipei
    command: ["-config.file=/config.yaml"]
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    ports:
      - 8081:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - apm
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 8082:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - apm


networks:
  apm:
    name: apm_network
    driver: bridge